#### dna-methylation-pipeline >>>>####

# Manual: https://www.bioinformatics.babraham.ac.uk/projects/bismark/Bismark_User_Guide.pdf
bismark:
  index: "{{cookiecutter.bismark_index}}"
  params: "{{cookiecutter.bismark}}"

bismark_methylation_extractor:
  params: "--comprehensive {{cookiecutter.bismark_methylation_extractor}}" # don't remove --comprehensive option since the outputs are defined by this option!

bismark2bedGraph:
  params: "--buffer_size 20G"
####<<<< dna-methylation-pipleine ####
