#### snakemake-pipeline-general >>>####
# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, strandedness).
# Units are techinical replicates (e.g. lanes, or resequencing of the same biological sample). If the 
# column "strandedness" is present (optional), value can be empty or has one of these values: none, yes
# or reverse.

skiptrim: {{cookiecutter.skiptrim}}
trimmer: "{{cookiecutter.trimmer}}" # trimmomatic or fastp

# specify the resources available for computational heavy rules, including: trimmomatic, samtools, bowtie2, bwa, deeptools...
nodes: {{cookiecutter.nodes}}
threads: {{cookiecutter.threads}}
mem: {{cookiecutter.mem}}

multiqc:
  params: ""

trimmomatic:
  # the trimming parameter, see manual: http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf
  trimmer: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:15"
  pe_adapter: "{{cookiecutter.pe_adapter}}"
  se_adapter: "{{cookiecutter.se_adapter}}"
  adapter_trimmer: ":2:30:10"

fastp:
  # manual: https://github.com/OpenGene/fastp
  pe_adapter: "{{cookiecutter.pe_adapter}}"
  se_adapter: "{{cookiecutter.se_adapter}}"
  extra: "{{cookiecutter.fastp}}"

####<<<< snakemake-pipeline-general ####
#### dna-methylation-pipeline >>>>####

# Manual: https://www.bioinformatics.babraham.ac.uk/projects/bismark/Bismark_User_Guide.pdf
bismark:
  index: "{{cookiecutter.bismark_index}}"
  params: "{{cookiecutter.bismark}}"

bismark_methylation_extractor:
  params: "--comprehensive {{cookiecutter.bismark_methylation_extractor}}" # don't remove --comprehensive option since the outputs are defined by this option!

bismark2bedGraph:
  params: "--buffer_size 20G"
####<<<< dna-methylation-pipleine ####
