import pandas as pd
from snakemake.utils import validate, min_version

#### Set minimum snakemake version ####
min_version("5.1.2")

#### Load config and sample sheets ####

configfile: "config.yaml"
#validate(config, schema="schemas/config.schema.yaml")

samples = pd.read_table(config["samples"]).set_index(["sample", "rep", "unit"], drop=False)
#validate(samples, schema="schemas/samples.schema.yaml")

#### target rules ####

# default only report CpG, uncomment to report all cytosine 
rule all:
    input:
        "output/qc/multiqc/multiqc.html",
        expand("output/bismark2bedGraph/{sample}_{context}/{sample}_bismark_bt2.{context}.bw", sample = samples["sample"], context = ["CpG", "CHG", "CHH"])
#        expand("output/bismark2bedGraph/{sample}_all/", sample = samples["sample"])

#### setup singularity ####

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
singularity: "docker://continuumio/miniconda3"

#### setup report ####
report: "report/workflow.rst"

#### load rules ####